name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:  # CD job (only runs if CI passed)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensures CD runs only if CI passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Exit if any command fails

            echo "🔹 Updating system..."
            sudo apt-get update -y

            echo "🔹 Deploying application..."
            cd /home/ubuntu/fastapi-book-project
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build --remove-orphans

            echo "✅ Deployment successful!"
